<?php

/**
 * @file
 * Module file for USDA eAuth.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_openid_connect_post_authorize().
 */
function usda_eauth_openid_connect_post_authorize(UserInterface $account, array $context) {

  // Get the zRoles utility service.
  /** @var \Drupal\usda_eauth\zRolesUtilitiesInterface $zroles_util */
  $zroles_util = \Drupal::service('usda_eauth.zroles');

  // eAuthId should be in $context['sub'].
  $eAuthId = $context['sub'];

  // Get the zRoles based on the eAuthID.
  $response = $zroles_util->getUserAccessRolesAndScopes($eAuthId);

  // Get the user info from zRoles response.
  $email = $zroles_util->getTokenValue($response, 'EmailAddress');
  $firstName = $zroles_util->getTokenValue($response, 'FirstName');
  $lastName = $zroles_util->getTokenValue($response, 'LastName');
  $roleId = $zroles_util->getTokenValue($response, 'ApplicationRoleId');
  $roleName = $zroles_util->getTokenValue($response, 'ApplicationRoleName');
  $roleEnum = $zroles_util->getTokenValue($response, 'ApplicationRoleEnumeration');
  $roleDisplay = $zroles_util->getTokenValue($response, 'ApplicationRoleDisplay');

  // Store the user info in the session.
  $session = \Drupal::request()->getSession();
  $session->set('eAuthId', $eAuthId);
  $session->set('EmailAddress', $email);
  $session->set('FirstName', $firstName);
  $session->set('LastName', $lastName);
  $session->set('ApplicationRoleId', $roleId);
  $session->set('ApplicationRoleName', $roleName);
  $session->set('ApplicationRoleEnumeration', $roleEnum);
  $session->set('ApplicationRoleDisplay', $roleDisplay);

  // Redirect to the proper route based on role.
  $destination = NULL;
  switch ($roleEnum) {
    case 'CIG_App_Admin':
    case 'CIG_APA':
      $destination = '/pods_admin_dashboard';
      break;
    case 'CIG_NSHDS':
    case 'CIG_NCDS':
    case 'CIG_APT':
      $destination = '/pods_awardee_dashboard';
      break;
  }
  if (!empty($destination)) {
    $session->set('openid_connect_destination', $destination);
  }
}
