<?php

Use Drupal\views\ViewExecutable;
Use Drupal\Core\Form\FormStateInterface;
/**
 * @file
 * Module file for Producer Operation Data Systems (PODS)
 */


 /*
	Implements hook_views_pre_render().
 */
function cig_pods_views_pre_render(ViewExecutable $view ) {
	if (isset($view) && ($view->storage->id() == 'producer_entry_form')) {
		$view->element['#attached']['library'][] =
		'cig_pods/producer_entry_form';
	}
	if (isset($view) && ($view->storage->id() == 'display_project')) {
		$view->element['#attached']['library'][] =
		'cig_pods/admin_details_display';
	}
	if (isset($view) && ($view->storage->id() == 'producer_display')) {
		$view->element['#attached']['library'][] =
		'cig_pods/admin_details_display';
	}
	if (isset($view) && ($view->storage->id() == 'awardee_organization_display')) {
		$view->element['#attached']['library'][] =
		'cig_pods/admin_details_display';
	}
	if (isset($view) && ($view->storage->id() == 'lab_test_profiles_display')) {
		$view->element['#attached']['library'][] =
		'cig_pods/admin_details_display';
	}
	if (isset($view) && ($view->storage->id() == 'methods_display')) {
		$view->element['#attached']['library'][] =
		'cig_pods/awardee_methods_details_display';
	}
	if (isset($view) && ($view->storage->id() == 'shmu_display')) {
		$view->element['#attached']['library'][] =
		'cig_pods/admin_details_display';
	}
}

function cig_pods_form_alter(&$form, FormStateInterface $form_state, $form_id) {

}