#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No version supplied: ./build_tarball <version>"
fi

echo "Installing patch utility..."
dnf install -y patch

echo "Installing composer..."
wget https://getcomposer.org/installer -O composer-installer.php
php composer-installer.php --filename=composer --install-dir=/usr/local/bin

cd pods_src

echo "Preparing files for build..."
cd ..
mkdir -p pods/web/modules/custom
cp pods_src/composer.json pods
cp -r pods_src/patches/ pods

echo "Copying custom modules..."
cp -r pods_src/web/modules/custom/* pods/web/modules/custom


echo "Building with composer..."
cd pods
export COMPOSER_ALLOW_SUPERUSER=1
/usr/local/bin/composer install

echo "Packaging tarball..."
cd ..
tar -cz pods/ > pods_$1.tar.gz

echo "Cleaning up..."
rm -rf composer-installer.php pods/ pods_src/

echo "Done!"