#!/bin/bash

# This script will COMPLETELY refresh the PODS codebase and container.
# THIS WILL UNDO ALL UNCOMMITTED CHANGES!

# Confirm that the user wants to do this...
read -r -p "PODS will be rebuilt. You will lose all data and uncommitted changes. Are you sure? [Y/n] " input
case $input in
      [yY][eE][sS]|[yY])
            echo "Rebuilding PODS..."
            ;;
      [nN][oO]|[nN])
            exit 0
            ;;
      *)
            echo "Invalid input..."
            exit 1
            ;;
esac


echo Please provide USDA Bitbucket Login information to install modules.
read -r -p "Enter Username: " username
while true; do
  read -s -p "Enter Password: " password1
  echo
  read -s -p "Confirm Password: " password2
  echo
  [ "$password1" = "$password2" ] && break
  echo "Passwords do not match. Please try again."
done


# Get this script's path and parent directory.
SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
PARENTPATH="$(dirname $SCRIPTPATH)"

# Shut down the Docker containers.
docker-compose -f $PARENTPATH/docker-compose.yml down

#Delete INSTALLED
rm $PARENTPATH/INSTALLED

#The following rm should be removed if we transfer over to a WSL2 enviornment
yes| rm -r $PARENTPATH/web

rm -f -- auth.json
echo "{\"http-basic\": {\"bitbucket.fpac.usda.gov\": {\"username\": \"$username\", \"password\": \"$password1\"}}}" > auth.json


# Build the Docker image.
docker-compose -f $PARENTPATH/docker-compose.yml build --no-cache

# Start up the Docker containers.
docker-compose -f $PARENTPATH/docker-compose.yml up
